backend:
  name: github
  repo: jonatanritter/jonatanritter.github.io
  branch: main

media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Corpo", name: "body", widget: "markdown" }

# Autenticação OAuth via GitHub
oauth:
  client_id: Ov23lixn4P3OjVW3NQvt 

